### ISSUE TITLE
Gitlab auth not working due to email verification failure

### ISSUE THREAD

**Issue by arctica** [Place1/wg-access-server#50]
I've configured Gitlab auth, am seeing the button to login via Gitlab in the UI, get to my Gitlab instance and grant access, get redirected to /auth/callback where I see the following message:

```oidc: get access token: oauth2: token expired and refresh token is not set```

Additionally I see the below panic in the logs which suggests it's a problem with verifying the email domain. When I remove the domain from the emailDomains config option, the auth starts working. Maybe wg-access-server does not get my email from Gitlab correctly. I guess it's trying to access parsed[1] on an empty string split.

```
2020/07/02 22:30:38 http: panic serving 171.6.x.x:49455: runtime error: index out of range [1] with length 1
goroutine 74 [running]:
net/http.(*conn).serve.func1(0xc000340aa0)
	/usr/local/go/src/net/http/server.go:1767 +0x139
panic(0xd2e780, 0xc0003bd460)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/place1/wg-access-server/pkg/authnz/authconfig.verifyEmailDomain(0xc0001d3c50, 0x1, 0x1, 0x0, 0x0, 0xc00010e500)
	/code/pkg/authnz/authconfig/oidc.go:149 +0x146
github.com/place1/wg-access-server/pkg/authnz/authconfig.(*OIDCConfig).callbackHandler.func1(0xeddbc0, 0xc0002280e0, 0xc000178400)
	/code/pkg/authnz/authconfig/oidc.go:104 +0x31f
net/http.HandlerFunc.ServeHTTP(0xc0005631d0, 0xeddbc0, 0xc0002280e0, 0xc000178400)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000cc3c0, 0xeddbc0, 0xc0002280e0, 0xc000178200)
	/go/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210 +0xe2
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000cc000, 0xeddbc0, 0xc0002280e0, 0xc000179f00)
	/go/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210 +0xe2
net/http.serverHandler.ServeHTTP(0xc000494b60, 0xeddbc0, 0xc0002280e0, 0xc000179f00)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc000340aa0, 0xedfec0, 0xc0001dd600)
	/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2928 +0x384
2020/07/02 22:31:54 http: panic serving 171.6.240.128:49460: runtime error: index out of range [1] with length 1
goroutine 107 [running]:
net/http.(*conn).serve.func1(0xc000159180)
	/usr/local/go/src/net/http/server.go:1767 +0x139
panic(0xd2e780, 0xc00041d100)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/place1/wg-access-server/pkg/authnz/authconfig.verifyEmailDomain(0xc0001d3c50, 0x1, 0x1, 0x0, 0x0, 0xc00010e370)
	/code/pkg/authnz/authconfig/oidc.go:149 +0x146
github.com/place1/wg-access-server/pkg/authnz/authconfig.(*OIDCConfig).callbackHandler.func1(0xeddbc0, 0xc0002281c0, 0xc000178800)
	/code/pkg/authnz/authconfig/oidc.go:104 +0x31f
net/http.HandlerFunc.ServeHTTP(0xc0005631d0, 0xeddbc0, 0xc0002281c0, 0xc000178800)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000cc3c0, 0xeddbc0, 0xc0002281c0, 0xc000178600)
	/go/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210 +0xe2
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000cc000, 0xeddbc0, 0xc0002281c0, 0xc000178400)
	/go/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210 +0xe2
net/http.serverHandler.ServeHTTP(0xc000494b60, 0xeddbc0, 0xc0002281c0, 0xc000178400)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc000159180, 0xedfec0, 0xc000460740)
	/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2928 +0x384
```

**Comment by Place1** [comment]
Thanks for reporting this. I've also had this problem. I'm hoping to focus more on this project soon and i'll do my best to resolve this one when i do.

**Comment by Place1** [comment]
@arctica this is now fixed.

the panic happens when the user hasn't set their gitlab email. it can be set here: gitlab.com/profile

in the above MR i've improved the logic so it doesn't crash and instead shows a message.

**Comment by arctica** [comment]
@Place1 thank you for fixing this so quickly. I do have my email set in Gitlab. It might be worth noting that this is a self hosted Gitlab CE instance. The account is set though to not publicly show the email which maybe also makes it unavailable via OIDC?

**Comment by arctica** [comment]
@Place1 unfortunately the fix didn't fully resolve the problem. I noticed the following panic in the logs when someone tried auth with Gitlab (which failed). The user then could not load the web interface at all until I gave them the link to log out and destroy their session.

```
2020/07/06 07:15:20 http: panic serving 188.x.x.x:57045: runtime error: invalid memory address or nil pointer dereference
goroutine 3940 [running]:
net/http.(*conn).serve.func1(0xc0000fc780)
	/usr/local/go/src/net/http/server.go:1767 +0x139
panic(0xc92f40, 0x1470450)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
main.main.func2(0x0, 0xc0003c4660, 0xc0045e7600)
	/code/main.go:140 +0x2a
github.com/place1/wg-access-server/pkg/authnz.(*AuthMiddleware).Wrap.func4(0xedd6e0, 0xc00051f6c0, 0xc0045e7600)
	/code/pkg/authnz/router.go:69 +0x3b2
net/http.HandlerFunc.ServeHTTP(0xc000577ef0, 0xedd6e0, 0xc00051f6c0, 0xc0045e7600)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000d89c0, 0xedd6e0, 0xc00051f6c0, 0xc0045e7400)
	/go/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210 +0xe2
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000d8000, 0xedd6e0, 0xc00051f6c0, 0xc0045e7100)
	/go/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210 +0xe2
net/http.serverHandler.ServeHTTP(0xc00051f880, 0xedd6e0, 0xc00051f6c0, 0xc0045e7100)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc0000fc780, 0xedf9e0, 0xc005c30b40)
	/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2928 +0x384
```
